### ISSUE TITLE
k8s-pvc-tagger crashing

### ISSUE THREAD

**Issue by mcbarzi** [mtougeron/k8s-pvc-tagger#71]
**Describe the bug**
Getting the ff error after a pvc has been deleted and recreated
```
E0117 23:07:54.796497       1 runtime.go:79] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 69 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x1c1ace0?, 0x32f11e0})
	/go/pkg/mod/k8s.io/apimachinery@v0.24.2/pkg/util/runtime/runtime.go:75 +0x99
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc00013b800?})
	/go/pkg/mod/k8s.io/apimachinery@v0.24.2/pkg/util/runtime/runtime.go:49 +0x75
panic({0x1c1ace0, 0x32f11e0})
	/usr/local/go/src/runtime/panic.go:838 +0x207
main.processPersistentVolumeClaim(0xc0001694d0)
	/build/kubernetes.go:367 +0x31f
main.watchForPersistentVolumeClaims.func1({0x1f14a20?, 0xc0001694d0})
	/build/kubernetes.go:114 +0x1f8
k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnAdd(...)
	/go/pkg/mod/k8s.io/client-go@v0.24.2/tools/cache/controller.go:232
k8s.io/client-go/tools/cache.(*processorListener).run.func1()
	/go/pkg/mod/k8s.io/client-go@v0.24.2/tools/cache/shared_informer.go:818 +0xaf
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x10000000011?)
	/go/pkg/mod/k8s.io/apimachinery@v0.24.2/pkg/util/wait/wait.go:155 +0x3e
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000523f38?, {0x235c4e0, 0xc000216060}, 0x1, 0xc000734000)
	/go/pkg/mod/k8s.io/apimachinery@v0.24.2/pkg/util/wait/wait.go:156 +0xb6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x0?, 0x3b9aca00, 0x0, 0x0?, 0xc000523f88?)
	/go/pkg/mod/k8s.io/apimachinery@v0.24.2/pkg/util/wait/wait.go:133 +0x89
k8s.io/apimachinery/pkg/util/wait.Until(...)
	/go/pkg/mod/k8s.io/apimachinery@v0.24.2/pkg/util/wait/wait.go:90
k8s.io/client-go/tools/cache.(*processorListener).run(0xc0005c4500?)
	/go/pkg/mod/k8s.io/client-go@v0.24.2/tools/cache/shared_informer.go:812 +0x6b
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1()
	/go/pkg/mod/k8s.io/apimachinery@v0.24.2/pkg/util/wait/wait.go:73 +0x5a
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
	/go/pkg/mod/k8s.io/apimachinery@v0.24.2/pkg/util/wait/wait.go:71 +0x85
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x1935b1f]

```
**To Reproduce**
We are currently using k8s-pvc-tagger:v1.0.1.
We installed the k8s pvc tagger which is working fine for a while.  We've installed ebs csi driver after.  
Previously, the PVCs are created by kubernetes.io/aws-ebs storage-provisioner(PVC annotation: volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/aws-ebs).  
We have recreated one of the pvcs and it got provisioned by ebs-csi-driver this time (PVC annotation: volume.beta.kubernetes.io/storage-provisioner: ebs.csi.aws.com)

The k8s-pvc-tagger started crashing after.

**Comment by mtougeron** [comment]
I'm having trouble replicating this. What version of the CSI drivers & Kubernetes are you running?

**Comment by dinhkim** [comment]
I also have the same issue with k8s-pvc-tagger:v1.0.1 on Kubernetes 1.23 and EBS CSI driver v1.13.0.
and the issue only happen if my PVC is created by StorageClass using `provisioner=kubernetes.io/aws-ebs`
Here is the yaml of PVC and PV

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"labels":{"app":"wordpress"},"name":"test-pv-claim","namespace":"test"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"5Gi"}},"storageClassName":"gp2-sc"}}
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: ebs.csi.aws.com
    volume.kubernetes.io/selected-node: ip-10-10-69-28.ap-southeast-1.compute.internal
    volume.kubernetes.io/storage-provisioner: ebs.csi.aws.com
    volume.kubernetes.io/storage-resizer: ebs.csi.aws.com
  creationTimestamp: "2023-03-13T07:21:41Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app: wordpress
  name: test-pv-claim
  namespace: test
  resourceVersion: "103958665"
  uid: 297ef030-7800-44f8-9780-509ca1481eef
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: gp2-sc
  volumeMode: Filesystem
  volumeName: pvc-297ef030-7800-44f8-9780-509ca1481eef
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  phase: Bound
---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/migrated-to: ebs.csi.aws.com
    pv.kubernetes.io/provisioned-by: kubernetes.io/aws-ebs
    volume.kubernetes.io/provisioner-deletion-secret-name: ""
    volume.kubernetes.io/provisioner-deletion-secret-namespace: ""
  creationTimestamp: "2023-03-13T07:21:45Z"
  finalizers:
  - kubernetes.io/pv-protection
  - external-attacher/ebs-csi-aws-com
  labels:
    topology.kubernetes.io/region: ap-southeast-1
    topology.kubernetes.io/zone: ap-southeast-1c
  name: pvc-297ef030-7800-44f8-9780-509ca1481eef
  resourceVersion: "103958308"
  uid: 67834cf4-9064-433f-a296-44525eb899c8
spec:
  accessModes:
  - ReadWriteOnce
  awsElasticBlockStore:
    fsType: ext4
    volumeID: vol-04afc8b7f18cf150e
  capacity:
    storage: 10Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: test-pv-claim
    namespace: test
    resourceVersion: "103776471"
    uid: 297ef030-7800-44f8-9780-509ca1481eef
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: topology.kubernetes.io/zone
          operator: In
          values:
          - ap-southeast-1c
        - key: topology.kubernetes.io/region
          operator: In
          values:
          - ap-southeast-1
  persistentVolumeReclaimPolicy: Delete
  storageClassName: gp2-sc
  volumeMode: Filesystem
status:
  phase: Bound
```

**Comment by dinhkim** [comment]
If I use k8s-pvc-tagger:v1.0.4, the crash issue is fixed but the EBS volume doesn't have the tags. And there is error `Cannot parse VolumeID` in log.

**Comment by dinhkim** [comment]
I think the issue can be fixed if the code is updated as follow
```
	if provisionedBy == "ebs.csi.aws.com" {
		if pv.Spec.CSI != nil {
			volumeID = pv.Spec.CSI.VolumeHandle
		} else {
                         volumeID = parseAWSEBSVolumeID(pv.Spec.AWSElasticBlockStore.VolumeID)
                }
```

**Comment by mtougeron** [comment]
Great, thanks for the update. I'll look into this fix tonight. I had a suspicion the issue was around the CSI migration which I don't have a lot of experience/test cases for.

**Comment by dinhkim** [comment]
@mtougeron can you review my PR https://github.com/mtougeron/k8s-pvc-tagger/pull/78 ?
